projects:
  Codegen Project:
    schemaPath: schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
      - src/API.ts
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: ap-northeast-1
        apiId: ybgh7kyfqnhdvlcqs6qcvftqvq
        frontend: javascript
        framework: react
        maxDepth: 2
