// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config =  {
    API: {
        GraphQL: {
          endpoint: 'https://alpa2abj6zhmrhduyrdxnsrcz4.appsync-api.ap-northeast-1.amazonaws.com/graphql',
          region: 'ap-northeast-1',
          defaultAuthMode: 'apiKey',
          apiKey: 'da2-7dfjizvoanaqjiu3mdlohowd7q'
        }
    }
};

export default config;